
DLIB_LEYE = (36,42)
DLIB_REYE = (42,48)
DLIB_NOSE = (27,36)
DLIB_MOUTH = (48,68)

FACE_SKIN = 1
LEFT_BROW = 2
RIGHT_BROW = 3
LEFT_EYE = 4
RIGHT_EYE = 5
LEFT_EAR = 7
RIGHT_EAR = 8
NOSE = 10
UPPER_LIP = 11
TEETH = 12
LOWER_LIP = 13

FACE = [FACE_SKIN,LEFT_BROW,RIGHT_BROW,LEFT_EYE,RIGHT_EYE,LEFT_EAR,RIGHT_EAR,NOSE,UPPER_LIP,TEETH,LOWER_LIP]